### ISSUE TITLE
Issue on MacOS

### ISSUE THREAD

**Issue by dootdoot1111** [Ganapati/RsaCtfTool#116]
Whenever i run `python3 RsaCtfTool.py` or just `./RsaCtfTool.py`, it shows 
`Traceback (most recent call last):
  File "./RsaCtfTool.py", line 21, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'`
I have installed module crypto but it still wont work. It was working a few months back.

**Comment by Yeboster** [comment]
Hello,

I had the same issue as you, and I've fixed it by installing crypto via easy_install not pip. 
So try to run `easy_install crypto` (I assume you are using pyenv).

I still haven't found the clue of this inconsistency, I'll check it later.

Also, I suggest you to switch to [PyCryptoDome](https://pypi.org/project/pycryptodome/) instead of unmaintained Crypto. It's a fork of it so it maintains the same module name, be careful to remove the old Crypto module.
