### ISSUE TITLE
Pollard p-1 not attempting

### ISSUE THREAD

**Issue by brothersw** [Ganapati/RsaCtfTool#312]
I have a public key that I know is susceptible to the pollard p-1 attack. Attempting it however it seems to not even attempt the attack, without doing any iterations, or timing out. Running --tests says that it works just fine.
[publickey.txt](https://github.com/Ganapati/RsaCtfTool/files/8356100/publickey.txt)
![Failed Cracking](https://user-images.githubusercontent.com/59877252/160252251-bb2d8347-33c5-41a6-a98e-a6bf4c76f560.png)

**Comment by MarcoMeinardi** [comment]
I fixed it in the above pull request. However, in order to factorize your key, you need to increment the number of primes used (line 21 in attack/single_key/pollard_p_1.py). I used 6543 in order to generate primes up to 0x10001 (I'm not sure if this makes sense, I don't understand this attack enough to tell, but it works).
