### ISSUE TITLE
import requests

### ISSUE THREAD

**Issue by Brutalmelon** [Ganapati/RsaCtfTool#93]
I've messed with this for about 2 hours now. There is no solution. I am convinced this code just does not function but my current problem is with importing requests there is no module named 'requests'

Traceback (most recent call last):
  File "./RsaCtfTool.py", line 22, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I have followed the "installation guide" step by step.. I have attempted to install it myself, I have literally installed ever single python package directly into the RsaCtfTool folder, I have tried basically everything in the world. 

Don't Work.

**Comment by Sjord** [comment]
I am sorry to hear that you have such troubles getting this to run.

The [`requests` module](https://pypi.org/project/requests/) is an external module that handles HTTP requests. It can be installed like this:

    pip install requests

When running that, it should finish with something like this:

> Successfully installed certifi-2019.11.28 chardet-3.0.4 idna-2.9 requests-2.23.0 urllib3-1.25.8

If you run `pip install` like this, it will try to install the package system-wide in `/usr/lib/python3/dist-packages` or something like that. If you want to install it just in the current directory for RsaCtfTool, it is a good idea to first create a [virtual environment](https://docs.python.org/3/tutorial/venv.html). A virtual environment is a little Python installation with its own packages. Create one like this:

    python3 -m venv venv

This will create a directory "venv". You can enable it like this:

    . venv/bin/activate

After enabling it, `python` refers to the Python in the virtual environment, and `pip` will install packages within the environment.

Instead of creating a virtual environment and using pip, there is also [pipenv](https://pipenv.pypa.io/en/latest/) that combines both, although I don't have much experience with that.

If you are still struggling with getting this working, it would be helpful to give some more information: which OS are you using, what have you tried, did you get any error messages?

RsaCtfTool is not really a polished Python package. It may take some effort getting it to work, but not two hours, like you said.

**Comment by Ganapati** [comment]
requests is in requirement.txt.
Did you run pip(3) install -r ./requirements.txt ?

**Comment by Brutalmelon** [comment]
Hey, I'm sorry for the late response. I definitely appreciate your replies, I haven't had a chance to give them a try yet but I will get back to you when I can.
